In [2]:
import numpy as np
from scipy import integrate

In [3]:
def LU(A):
    n = len(A)
    L,U = np.identity(n,dtype=float), np.array(A,dtype=float)
    for i in range(n-1):
        for k in range(i+1,n):
            a = U[k][i] / U[i][i]
            L[k][i] = a
            U[k] = U[k] - a*U[i]
    return L,U
 
A=np.array([[2,-1,0],
            [-1,2,-1]
            ,[0,-1,2]])
L, U = LU(A)
print(L,"\n", U)
print(L@U)



[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]] 
 [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


In [4]:
def systemeInferieure(L,b):
    n = len(L)
    X = np.zeros(n)
    for i in range(n):
        sum = 0
        for j in range(i):
            sum += L[i][j] * X[j]
        X[i] = (b[i] - sum)/L[i][i]
    return X

L = np.array([[1,0]
             ,[7,8]])
b = np.array([9,8])
X = systemeInferieure(L,b)
print(L @ X)

[9. 8.]


In [5]:
def systemeSuperieure(U,b):
    n = len(U)
    X = np.zeros(n)
    for i in range(n)[::-1]:
        sum = 0
        for j in range(i+1,n):
            sum += U[i][j] * X[j]
        X[i] = (b[i] - sum)/U[i][i] 
    return X

U = np.array([[100,9,2]
             ,[0,7,10],
              [0,0,4]])
b = np.array([10,8,9])
X = systemeSuperieure(U,b)
print(U @ X)


[10.  8.  9.]


In [6]:
def resolutionLU(A,b):
    L, U = LU(A)
    Y = systemeInferieure(L,b)
    X = systemeSuperieure(U,Y)
    return X

A = np.array([[18,6,-6],
             [6,21,0],
             [-6,0,15]])
b = [24,27,-6]
X = resolutionLU(A,b)
print(A @ X)
print(X)

[24. 27. -6.]
[1. 1. 0.]


In [21]:
def Jacobi2(A,b,x0,k):
    n = len(A)
    M = A.diagonal()
    M = [1/M[i] for i in range(n)]
    M = np.diag(M)
    N = -np.array(A)
    np.fill_diagonal(N,0)
    for i in range(k):
        x0 = M@(N @ x0 + b)
    return x0
A = np.array([[10,2,3],
             [10,11,5],
             [8,2,9]])
b = [1,2,3]
Xj = Jacobi(A,b,np.array([1,1,1]),200)
print(Xj)

[-0.00682594  0.03754266  0.33105802]


In [27]:
def Jacobi(A,b,x0,k):
    n=len(A)
    xk = x0
    xkeep = np.zeros(n)
    for _ in range(k):
        for i in range(n):
            s = sum(A[i][j]*xk[j] for j in range(n) if j!=i)
            xkeep[i] = 1/A[i][i] * (b[i]-s)
        xk = xkeep
    return xk
Xj=Jacobi(A,b,np.array([1,1,1]),300)
print(A@Xj)

[1. 2. 3.]


In [25]:
def GaussSeidel(A,b,x0,k) :
    n=len(x0)
    xk=x0
    xkeep=np.zeros(n)
    for _ in range(k):
        for i in range(n):
            s1 = sum(A[i][j]*xk[j] for j in range(i+1,n))
            s2 = sum(A[i][j]*xkeep[j] for j in range(i))
            xkeep[i] = 1/A[i][i] * (b[i]-s1-s2)
        xk=xkeep
    return xk
Xj=GaussSeidel(A,b,np.array([1,1,1]),300)
print(A@Xj)

[1. 2. 3.]


In [26]:
def Gradient(A,b,x0,k):
    xk=x0
    for i in range(k):
        xk=(np.eye(n,dtype=float)-alpha@A)@xk+alpha*b
    return xk
Xj=GaussSeidel(A,b,np.array([1,1,1]),300)
print(A@Xj)

[1. 2. 3.]
